Allow composing `Retryable` annotation with @AliasFor recover method
spring-projects/spring-retry pull request #313
Opened 2022-10-03 22:53 UTC by gmedici

Creating a custom annotation composing `@Retryable` will not get the actual recover argument value even when the recover method is annotated with `@AliasFor`. Eg:

```
@Target({ ElementType.METHOD, ElementType.TYPE })
@Retention(RetentionPolicy.RUNTIME)
@Documented
@Retryable(maxAttempts = 4)
public @interface ComposedRetryable {
    @AliasFor(annotation = Retryable.class, attribute = "recover")
    String recover() default "";
}
```

The reason is that `RecoverAnnotationRecoveryHandler` is still using AnnotationUtils.findAnnotation() instead of AnnotatedElementUtils.findMergedAnnotation()

2022-10-04 13:40 UTC, artembilan requested changes
It also would be great if you add some explanation and sample for this feature in the README of the project: https://github.com/spring-projects/spring-retry#declarative-retry.

Thank you!

2022-10-04 13:40 UTC, artembilan commented on src/test/java/org/springframework/retry/annotation/RecoverAnnotationRecoveryHandlerTests.java
> +import java.lang.annotation.*;
Please, don't use an asterisk imports.
Please, add your name to the `@author` list of all the effected classes.
And update their Copyright to the current year.

2022-10-05 12:47 UTC, artembilan requested changes

2022-10-05 12:59 UTC, gmedici commented on README.md
> +With version 2.0 and later it is also possible to use `@AliasFor` annotation on the `recover` method also, so that you can further extend the versatility of your custom annotations and allow the `rec
Great, I was gonna ask you the backport it anyway. Allright I'll fix it.

2022-10-05 14:47 UTC, merged

2022-10-05 14:51 UTC, artembilan commented
... and back-ported to `1.3.x` as https://github.com/spring-projects/spring-retry/commit/2e7a73c15af02c5b0e5c4e86efb69b509a74f292 after some minor conflict resolution.

@gmedici ,

thank you very much for contribution; looking forward for more!