Overhaul Javadoc of RestTemplateBuilder
spring-projects/spring-retry pull request #359
Opened 2023-06-06 12:45 UTC by aahlenst

While working on `RestTemplateBuilder`, I noticed a couple of typos, some confusing explanations, a lack of descriptions of error conditions, and that it does not always follow the Spring Framework style guide. So I tried my best to improve it.

If you're not happy with some choices I made, feel free to edit it yourself.

2023-06-06 14:56 UTC, artembilan requested changes
Just great!

Please, update the Copyright of the affected classes to the current year and add your name to the `@author` list.

Thanks

2023-06-06 14:56 UTC, artembilan commented on src/main/java/org/springframework/retry/support/RetryTemplateBuilder.java
> +	 * Appends all provided {@code listeners} to {@link RetryTemplate}'s list of
The method Javadoc must be imperative: https://github.com/spring-projects/spring-framework/wiki/Code-Style#javadoc-formatting

I see that in some place you have it fixed, but not here.

2023-06-07 10:03 UTC, aahlenst commented
Problems should be fixed. As far as I can see, I'm already mentioned as an`@author` on all the classes.

2023-06-07 13:05 UTC, merged

2023-06-07 13:06 UTC, artembilan commented
@aahlenst ,

thank you for contribution; looking forward for more!

2023-06-21 18:37 UTC, xak2000 commented
Small correction. This task is not about `RestTemplateBuilder` as stated in the title, but about `RetryTemplateBuilder`. :)

Noticed "Overhaul Javadoc of RestTemplateBuilder" in v2.0.2 release notes and was very surprised. 😄

2023-06-21 18:38 UTC, artembilan commented
Fixed.
Thank you! 😄