fix: RetryTemplate aot hints
spring-projects/spring-retry pull request #471
Opened 2024-09-16 12:53 UTC by klopfdreh

fixes: https://github.com/spring-projects/spring-retry/issues/470

2024-09-18 17:14 UTC, artembilan requested changes
As we discussion in the Spring Cloud [issue](https://github.com/spring-cloud/spring-cloud-config/pull/2456) , it would be better to avoid reflection altogether.
So, please, consider to rework your contribution into a setter for such a `log` instead.
Thanks

2024-09-18 17:52 UTC, klopfdreh commented
Hey - sure 👍 - I am going to change it, tomorrow.

2024-09-19 14:43 UTC, artembilan requested changes

2024-09-19 15:11 UTC, klopfdreh commented on src/main/java/org/springframework/retry/support/RetryTemplate.java
> +	 * @param logger the logger the retry template uses for logging
done.

2024-09-19 15:13 UTC, artembilan commented on src/main/java/org/springframework/retry/support/RetryTemplate.java
> +	 * @param logger the logger the retry template uses for logging
No need to say `done/fixed/OK` if you just pushed the fix.
I'll see it in the next commit in the PR.
Also, don't squash commits to preserver changes history.
We squash them on merge to upstream.
Thanks

2024-09-19 15:24 UTC, merged

2024-09-19 15:25 UTC, artembilan commented
@klopfdreh ,

thank you for contribution; looking forward for more!

Now it is time to raise an issue in Spring Cloud Config to use this new setter instead of reflection.

2024-09-19 16:04 UTC, klopfdreh commented
I already prepared the changes and I am going to create the PR and the issue, tomorrow.