Add default hashCode implementation to RetryConfiguration.AnnotationClassOrMethodPointcut
spring-projects/spring-retry pull request #472
Opened 2024-09-23 15:13 UTC by NorsaG

This pull request introduces a default implementation of hashCode for RetryConfiguration.AnnotationClassOrMethodPointcut.

I discovered that using Spring Cloud with configuration refreshing (specifically the RefreshScope annotation and ConfigServicePropertySourceLocator as part of spring-cloud-config) can lead to a "java.lang.OutOfMemoryError: Metaspace". This occurs because the ConfigServicePropertySourceLocator is re-initialized with every refresh. Due to the absence of a hashCode implementation, proxies for this class are regenerated each time, which causes them to be stored in the org.springframework.cglib.core.internal.LoadingCache. This results in an excessive accumulation of generated proxies in memory, ultimately leading to metaspace overflow.

2024-09-23 15:13 UTC, pivotal-cla commented
@NorsaG Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-retry&pullRequestId=472)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-retry&pullRequestId=472) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2024-09-23 15:14 UTC, pivotal-cla commented
@NorsaG Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-retry&pullRequestId=472)!

2024-09-23 16:50 UTC, artembilan requested changes
Update Copyright of the changed class to actual year.
Add you name to the `@author` list.

Thanks

2024-09-23 16:50 UTC, artembilan commented on src/main/java/org/springframework/retry/annotation/RetryConfiguration.java
> +			return Objects.hash(methodResolver);
Please, add `this.` prefix.

2024-09-23 17:19 UTC, NorsaG commented
Fit the PR according to the comment.

2024-09-23 18:15 UTC, merged

2024-09-23 18:15 UTC, artembilan commented
@NorsaG ,

thank you for contribution; looking forward for more!

2025-05-21 03:14 UTC, NorsaG commented
@artembilan, I’ve finally published an article with a detailed explanation of a real-world case of this issue: https://shorturl.at/HVa0Y
I think it could be interesting

2025-05-22 20:03 UTC, artembilan commented
Hi @NorsaG !

The article is great!
Sorry to cause so much pain and great to see how you have figured out everything.

Would you mind from your experience point me where exactly that `RetryConfiguration.AnnotationClassOrMethodPointcut` is used a part of cache key.

Thank you!

2025-05-23 07:44 UTC, NorsaG commented
Yes, of course.

I've tried to reproduce the same problem again. It was a bit tricky due to the complexity of our project and the ongoing component upgrades. 

In Picture 1, you can observe the LoadingCache object at the moment of retrieving an object from the cache (I paused at a debug point after several configuration updates from the config server).
![1](https://github.com/user-attachments/assets/ae52017b-11ab-46b4-858c-82e0630e730c)

In Picture 2, nothing is found in the cache. 
![2](https://github.com/user-attachments/assets/53fb0387-5d55-4945-8461-84810d3b79b8)

In Picture 3, I have highlighted the path to the pointcut.  
![3](https://github.com/user-attachments/assets/7c2aff74-c8e8-464f-bb90-d5dbe072ed86)

(I'm not entirely sure, but I highlighted the "methodMatcherKey" string because it is unique for all EnhancerKeys in the cache.)

2025-05-23 11:34 UTC, artembilan commented
Thanks. I see now.
So, the path is like this: 
1. `org.springframework.aop.framework.AdvisedSupport`:
```
private List<Advisor> advisorKey = this.advisors;
```
Where one of them is our `RetryConfiguration`.
2. `org.springframework.aop.framework.CglibAopProxy.ProxyCallbackFilter`:
```
public int hashCode() {
			return this.advised.getAdvisorKey().hashCode();
		}
```
3. `org.springframework.cglib.proxy.Enhancer.createHelper()`:
```
		Object key = new EnhancerKey((superclass != null ? superclass.getName() : null),
				(interfaces != null ? Arrays.asList(ReflectUtils.getNames(interfaces)) : null),
				(filter == ALL_ZERO ? null : new WeakCacheKey<>(filter)),
				Arrays.asList(callbackTypes),
				useFactory,
				interceptDuringConstruction,
				serialVersionUID);
```

So, apparently the problem has gone with that our `hashCode()` fix just because the `RetryConfiguration` uses a default implementation based on its properties.

I see how this was hard to catch and even harder to determine what simple fix has to be.

Thank you again!

I will look now to other `Advisor`  implementations for similar problem.

2025-05-23 17:01 UTC, NorsaG commented
That was a really interesting issue! It was a bit of a pain to track down the cause since the production service wasn’t accessible, but I’m happy I could help out

2025-05-23 19:44 UTC, artembilan commented
I was wrong with that sentence:

> So, apparently the problem has gone with that our `hashCode()` fix just because the `RetryConfiguration` uses a default implementation based on its properties.

It is not about properties, but object identity by default: https://varoa.net/jvm/java/openjdk/biased-locking/2017/01/30/hashCode.html.

And you were right, the `AdvisorKeyEntry` is the root of the logic:
```
this.methodMatcherKey = pointcut.getMethodMatcher().toString();
```
That `getMethodMatcher()` is like this for our `RetryConfiguration.AnnotationClassOrMethodPointcut`:
```
	public final MethodMatcher getMethodMatcher() {
		return this;
	}
```

and that default `toString()` implementation is:
```
    public String toString() {
        return getClass().getName() + "@" + Integer.toHexString(hashCode());
    }
```
So, that's where we got that discrepancy because default `hashCode()` is an identity of the new object after refresh scope.

2025-05-25 10:54 UTC, NorsaG commented
I read the article above, but in my opinion, the author described a some different set of issues.

According to the official API note:

> It is generally necessary to override the [hashCode](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/Object.html#hashCode()) method whenever this method is overridden, so as to maintain the general contract for the hashCode method, which states that equal objects must have equal hash codes.

[Source: Object.equals() documentation](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/Object.html#equals(java.lang.Object))

This was a significant problem in our case.

Another point is the `toString()` method. While debugging the latest version of the code, I noticed it, specifically when I saw the default `toString()` output for `methodMatcherKey`.
It might be a good idea to override this method, especially considering its usage here:
`this.methodMatcherKey = pointcut.getMethodMatcher().toString();`

2025-05-27 14:26 UTC, artembilan commented
I think `toString()` would be that unnecessary extra.
The main point that we have missed to implement properly `equals()` and `hashCode()`.
Nothing more to worry about!